name: Checks

on: [push, pull_request]

jobs:
  unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y zlib1g-dev libxml2-dev libxslt-dev libcurl4-gnutls-dev libsqlite3-dev libjansson-dev libevent-dev libxml2-utils qtbase5-dev qtwebengine5-dev qt5-qmake qt5-default xmlstarlet ffmpeg sshpass
            sudo curl -L http://stahlworks.com/dev/sfk/sfk-linux-64.exe -o /usr/local/bin/sfk
            sudo chmod +x /usr/local/bin/sfk
          fi
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake libxslt sqlite jansson libevent qt sfk xmlstarlet ffmpeg
          fi
          sudo pip install git+https://github.com/vi/mkvparse.git
      - name: ZenLib
        run: |
          git -C .. clone --depth=1 https://github.com/MediaArea/ZenLib.git
          pushd ../ZenLib/Project/GNU/Library
            autoreconf -if
            ./configure --enable-static
            make
          popd
      - name: MediaInfoLib
        run: |
          git -C .. clone --depth=1 https://github.com/MediaArea/MediaInfoLib.git
          pushd ../MediaInfoLib/Project/GNU/Library
            autoreconf -if
            ./configure --enable-static
            make
          popd
      - name: Configure
        run: |
          cd Project/GNU/CLI
          autoreconf -if
          ./configure
      - name: Build
        run: |
          cd Project/GNU/CLI
          make
      - name: Check files
        run: |
          cd Project/GNU/CLI
          make clone_sample_files clone_checks_files
      - name: Check
        run: |
          cd Project/GNU/CLI
          make check
      - name: Configure GUI
        run: |
          cd Project/Qt
          export PATH=/usr/local/opt/qt/bin:$PATH
          ./prepare INCLUDEPATH+=/usr/local/include CONFIG+=c++11 -after QMAKE_MACOSX_DEPLOYMENT_TARGET=10.9
      - name: Build GUI
        run: |
          cd Project/Qt
          export PATH=/usr/local/opt/qt/bin:$PATH
          make
