name: Build_libs

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        library_type: [static, shared]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cmake_preset_name: conan-release
          - os: macos-latest
            cmake_preset_name: conan-release
          - os: windows-latest
            cmake_preset_name: conan-default
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          cache: 'pip' # caching pip dependencies
      - name: "install dependencies"  # use conan package manager to install c and c++ dependencies
        run: |
          pip install --disable-pip-version-check uv
          uvx conan profile detect
          uvx conan install -of build --requires="zlib/1.3.1" --requires="libxslt/1.1.43" --requires="libxml2/2.13.8" --requires="libzen/0.4.38" --requires="libmediainfo/22.03" --build=missing -g CMakeDeps -g CMakeToolchain
      - name: Configure cmake
        run: |
          cmake --preset ${{ matrix.cmake_preset_name }} -D BUILD_SHARED_LIBS=${{ matrix.library_type == 'static' &&  'NO' || 'YES'}}
      - name: Build
        run: |
          cmake --build --preset conan-release
      - name: Install
        run: |
          cmake --install build --prefix sample_prefix